### ISSUE TITLE
TextInput can't be dragged

### ISSUE THREAD

**Issue by Firetuy** [kmagiera/react-native-gesture-handler#668]
I'm using react-native-tab-view, and i can't swipe the TextInput

**Comment by bajanitin** [comment]
I am also facing this issue where PanGestureHandler is not working with TextInput on Android. It works on iOS though.

I have put PanGesture, Pinchgesture, RotateGesture on TextInput as per steps given in the example. Everything works fine on iOS however on Android only Pinchgesture works. Rotate & Pan are not working on Android. I am using Perspective as 200

**Comment by Fantasim** [comment]
Same.

**Comment by Ashkan-Oliaie** [comment]
I havea  textInput nested in my PanGesture and , the pan is working till I focus the textinput then it won't work,

**Comment by Ashkan-Oliaie** [comment]
@bajanitin 
 Although the PangestureHandler doesn't get triggered when u begin the touch on the textInput .
I happened to realize that if you define the textInput on different screen than the PanHandler the PanHandler works just fine.
Simply create another component for your textInput
:)

**Comment by yairopro** [comment]
Hi

**Any news about this issue ?**

I have to put the `TextInput` inside the `PanGestureHandler`. The pan doesn't give any velocity when the start dragging point is from inside the `TextInput`. I'm using the `react-native-gesture-handler`'s `TextInput`.

**Comment by pzxbc** [comment]
I also encounter this problem. It's not worked for android

**Comment by shyrynaz** [comment]
Anyone found a solution to this? Am also facing the same problem.

**Comment by tonypeng** [comment]
+1, am trying to implement pinch-to-zoom on an already focused TextInput to control the font size of the TextInput. Looks like the TextInput is intercepting all touch events.

**Comment by sa8ab** [comment]
+1

**Comment by osdnk** [comment]
I fixed it with https://github.com/rainbow-me/rainbow/pull/1367/files#diff-d699d7f0a9a22f930dea0a0656bcaeae3d1a440a09566a40bc1f08dd3cab9002R56

**Comment by osdnk** [comment]
Probably it's not a generic solution, but works for me and I have no time to dig into this deeper. If you'd like feel free to make a PR with this. 

cc: @jakub-gonet

**Comment by Noitidart** [comment]
Thanks @osdnk for you fix - if possible react-native-guesture-handler team to get this in that would be awesome.

**Comment by bmitioglov** [comment]
I still have this issue with GH 2.9.0, Text input doesn't react to swipes
