### ISSUE TITLE
Nested touchable inside Swipeable

### ISSUE THREAD

**Issue by brunolemos** [kmagiera/react-native-gesture-handler#784]
### Expected Behavior

![Kapture 2019-10-05 at 16 34 43](https://user-images.githubusercontent.com/619186/66259912-209c5780-e78e-11e9-88f3-9a335a8c7d26.gif)

### Current Behavior

![Kapture 2019-10-05 at 16 57 32](https://user-images.githubusercontent.com/619186/66260162-40814a80-e791-11e9-9047-35393c58b0a4.gif)

### Description

I'm using the `Swipeable` component. 

To avoid triggering the `onPress` by mistake, I'm also using the `TouchableOpacity` from `react-native-gesture-handler`.

But I want to have another touchable inside of this card, nested.

When clicking at `#131` or `mentioned`, it should trigger only this touchable, like the first gif above. But it is also triggering the whole card touchable, like the second gif. 

How to achieve this?
Ideally the outer touchable should not even change opacity.
I tried using `e.preventDefault` but the outer touchable is firing before the inner nested touchable.

**Comment by brunolemos** [comment]
Upgrading to `react-native@0.61+` and to the latest version of `react-native-gesture-handler` fixed the issue.

**Comment by brunolemos** [comment]
Only iOS is working as expected, Android still has the wrong behavior. Both touchables get triggered.
@kmagiera Any workaround for this?

I noticed that the `onPress` handler doesn't receive an `event` argument. If they did, I could call `e.preventDefault()` once and check `e.isDefaultPrevented()` second as a workaround. 

https://github.com/kmagiera/react-native-gesture-handler/blob/533f8b042660d5d19eb54e4d99ea3b39a8a84339/touchables/GenericTouchable.js#L211

**Comment by leteach** [comment]
Any fix for this? I am experiencing it as well. Upgraded our `react-native-gesture-handler` version to 1.4.1 and still seeing the same problem. Everything works fine in iOS but Android is trigger both onPress events for the two separate touchable events.

**Comment by leteach** [comment]
I had to create a separate component for Android that imported the parent ToucableWithoutFeedback from react-native and the child TouchableOpacity from react-native-gesture-handler. That had to be conditionally rendered based one Platform.OS. It is hacky as hell but it works for now.

**Comment by brunolemos** [comment]
@leteach the parent `onPress` don't get triggered that way? Are you using `Swipeable` as well? I think I can't use `ToucableWithoutFeedback` from react-native on a Swipeable because that would cause issues when swiping (unwaned press events).

**Comment by leteach** [comment]
@brunolemos The issue occurs regardless of whether the parent is a TouchableOpacity or TouchableWithoutFeedback. It is happening specifically inside a component that utilizes a library called `react-native-snap-carousel`, which I suspect has a Swipeable in it.

**Comment by brunolemos** [comment]
The issue seems to be unrelated to Swipeable, it's caused by any nested Touchables if they are imported from rngh. Updated the title and description.

@kmagiera here's a small repro: https://snack.expo.io/@brunolemos/rngh-nested-touchable-android-bug

**Comment by brunolemos** [comment]
#486 fixes this bug 🎉

Here's the patch that can be applied using [patch-package](https://github.com/ds300/patch-package):

<details>

<summary>patches/react-native-gesture-handler+1.5.2.patch</summary>

```patch
diff --git a/node_modules/react-native-gesture-handler/android/build/generated/source/buildConfig/androidTest/debug/com/swmansion/gesturehandler/react/test/BuildConfig.java b/node_modules/react-native-gesture-handler/android/build/generated/source/buildConfig/androidTest/debug/com/swmansion/gesturehandler/react/test/BuildConfig.java
new file mode 100644
index 0000000..dc64a01
--- /dev/null
+++ b/node_modules/react-native-gesture-handler/android/build/generated/source/buildConfig/androidTest/debug/com/swmansion/gesturehandler/react/test/BuildConfig.java
@@ -0,0 +1,13 @@
+/**
+ * Automatically generated file. DO NOT MODIFY
+ */
+package com.swmansion.gesturehandler.react.test;
+
+public final class BuildConfig {
+  public static final boolean DEBUG = Boolean.parseBoolean("true");
+  public static final String APPLICATION_ID = "com.swmansion.gesturehandler.react.test";
+  public static final String BUILD_TYPE = "debug";
+  public static final String FLAVOR = "";
+  public static final int VERSION_CODE = 1;
+  public static final String VERSION_NAME = "1.0";
+}
diff --git a/node_modules/react-native-gesture-handler/android/build/generated/source/buildConfig/debug/com/swmansion/gesturehandler/react/BuildConfig.java b/node_modules/react-native-gesture-handler/android/build/generated/source/buildConfig/debug/com/swmansion/gesturehandler/react/BuildConfig.java
new file mode 100644
index 0000000..bd6dac7
--- /dev/null
+++ b/node_modules/react-native-gesture-handler/android/build/generated/source/buildConfig/debug/com/swmansion/gesturehandler/react/BuildConfig.java
@@ -0,0 +1,18 @@
+/**
+ * Automatically generated file. DO NOT MODIFY
+ */
+package com.swmansion.gesturehandler.react;
+
+public final class BuildConfig {
+  public static final boolean DEBUG = Boolean.parseBoolean("true");
+  public static final String LIBRARY_PACKAGE_NAME = "com.swmansion.gesturehandler.react";
+  /**
+   * @deprecated APPLICATION_ID is misleading in libraries. For the library package name use LIBRARY_PACKAGE_NAME
+   */
+  @Deprecated
+  public static final String APPLICATION_ID = "com.swmansion.gesturehandler.react";
+  public static final String BUILD_TYPE = "debug";
+  public static final String FLAVOR = "";
+  public static final int VERSION_CODE = 1;
+  public static final String VERSION_NAME = "1.0";
+}
diff --git a/node_modules/react-native-gesture-handler/android/build/intermediates/aapt_friendly_merged_manifests/debug/aapt/AndroidManifest.xml b/node_modules/react-native-gesture-handler/android/build/intermediates/aapt_friendly_merged_manifests/debug/aapt/AndroidManifest.xml
new file mode 100644
index 0000000..ff3611b
--- /dev/null
+++ b/node_modules/react-native-gesture-handler/android/build/intermediates/aapt_friendly_merged_manifests/debug/aapt/AndroidManifest.xml
@@ -0,0 +1,11 @@
+<?xml version="1.0" encoding="utf-8"?>
+<manifest xmlns:android="http://schemas.android.com/apk/res/android"
+    package="com.swmansion.gesturehandler.react"
+    android:versionCode="1"
+    android:versionName="1.0" >
+
+    <uses-sdk
+        android:minSdkVersion="16"
+        android:targetSdkVersion="28" />
+
+</manifest>
\ No newline at end of file
diff --git a/node_modules/react-native-gesture-handler/android/build/intermediates/aapt_friendly_merged_manifests/debug/aapt/output.json b/node_modules/react-native-gesture-handler/android/build/intermediates/aapt_friendly_merged_manifests/debug/aapt/output.json
new file mode 100644
index 0000000..b5c89ae
--- /dev/null
+++ b/node_modules/react-native-gesture-handler/android/build/intermediates/aapt_friendly_merged_manifests/debug/aapt/output.json
@@ -0,0 +1 @@
+[{"outputType":{"type":"AAPT_FRIENDLY_MERGED_MANIFESTS"},"apkData":{"type":"MAIN","splits":[],"versionCode":1,"versionName":"1.0","enabled":true,"outputFile":"react-native-gesture-handler-debug.aar","fullName":"debug","baseName":"debug"},"path":"AndroidManifest.xml","properties":{"packageId":"com.swmansion.gesturehandler.react","split":""}}]
\ No newline at end of file
diff --git a/node_modules/react-native-gesture-handler/android/build/intermediates/incremental/packageDebugResources/compile-file-map.properties b/node_modules/react-native-gesture-handler/android/build/intermediates/incremental/packageDebugResources/compile-file-map.properties
new file mode 100644
index 0000000..4cdde7f
--- /dev/null
+++ b/node_modules/react-native-gesture-handler/android/build/intermediates/incremental/packageDebugResources/compile-file-map.properties
@@ -0,0 +1 @@
+#Sun Dec 08 19:48:36 BRST 2019
diff --git a/node_modules/react-native-gesture-handler/android/build/intermediates/incremental/packageDebugResources/merger.xml b/node_modules/react-native-gesture-handler/android/build/intermediates/incremental/packageDebugResources/merger.xml
new file mode 100644
index 0000000..4722743
--- /dev/null
+++ b/node_modules/react-native-gesture-handler/android/build/intermediates/incremental/packageDebugResources/merger.xml
@@ -0,0 +1,2 @@
+<?xml version="1.0" encoding="utf-8"?>
+<merger version="3"><dataSet aapt-namespace="http://schemas.android.com/apk/res-auto" config="main$Generated" generated="true" ignore_pattern="!.svn:!.git:!.ds_store:!*.scc:.*:&lt;dir>_*:!CVS:!thumbs.db:!picasa.ini:!*~"><source path="/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/res"/><source path="/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/build/generated/res/rs/debug"/><source path="/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/build/generated/res/resValues/debug"/></dataSet><dataSet aapt-namespace="http://schemas.android.com/apk/res-auto" config="main" generated-set="main$Generated" ignore_pattern="!.svn:!.git:!.ds_store:!*.scc:.*:&lt;dir>_*:!CVS:!thumbs.db:!picasa.ini:!*~"><source path="/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/res"/><source path="/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/build/generated/res/rs/debug"/><source path="/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/build/generated/res/resValues/debug"/></dataSet><dataSet aapt-namespace="http://schemas.android.com/apk/res-auto" config="debug$Generated" generated="true" ignore_pattern="!.svn:!.git:!.ds_store:!*.scc:.*:&lt;dir>_*:!CVS:!thumbs.db:!picasa.ini:!*~"><source path="/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/debug/res"/></dataSet><dataSet aapt-namespace="http://schemas.android.com/apk/res-auto" config="debug" generated-set="debug$Generated" ignore_pattern="!.svn:!.git:!.ds_store:!*.scc:.*:&lt;dir>_*:!CVS:!thumbs.db:!picasa.ini:!*~"><source path="/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/debug/res"/></dataSet><mergedItems/></merger>
\ No newline at end of file
diff --git a/node_modules/react-native-gesture-handler/android/build/intermediates/library_manifest/debug/AndroidManifest.xml b/node_modules/react-native-gesture-handler/android/build/intermediates/library_manifest/debug/AndroidManifest.xml
new file mode 100644
index 0000000..ff3611b
--- /dev/null
+++ b/node_modules/react-native-gesture-handler/android/build/intermediates/library_manifest/debug/AndroidManifest.xml
@@ -0,0 +1,11 @@
+<?xml version="1.0" encoding="utf-8"?>
+<manifest xmlns:android="http://schemas.android.com/apk/res/android"
+    package="com.swmansion.gesturehandler.react"
+    android:versionCode="1"
+    android:versionName="1.0" >
+
+    <uses-sdk
+        android:minSdkVersion="16"
+        android:targetSdkVersion="28" />
+
+</manifest>
\ No newline at end of file
diff --git a/node_modules/react-native-gesture-handler/android/build/intermediates/manifest_merge_blame_file/debug/manifest-merger-blame-debug-report.txt b/node_modules/react-native-gesture-handler/android/build/intermediates/manifest_merge_blame_file/debug/manifest-merger-blame-debug-report.txt
new file mode 100644
index 0000000..e5c319e
--- /dev/null
+++ b/node_modules/react-native-gesture-handler/android/build/intermediates/manifest_merge_blame_file/debug/manifest-merger-blame-debug-report.txt
@@ -0,0 +1,13 @@
+1<?xml version="1.0" encoding="utf-8"?>
+2<manifest xmlns:android="http://schemas.android.com/apk/res/android"
+3    package="com.swmansion.gesturehandler.react"
+4    android:versionCode="1"
+5    android:versionName="1.0" >
+6
+7    <uses-sdk
+8        android:minSdkVersion="16"
+8-->/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml
+9        android:targetSdkVersion="28" />
+9-->/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml
+10
+11</manifest>
diff --git a/node_modules/react-native-gesture-handler/android/build/intermediates/manifest_merge_blame_file/debugAndroidTest/manifest-merger-blame-debug-androidTest-report.txt b/node_modules/react-native-gesture-handler/android/build/intermediates/manifest_merge_blame_file/debugAndroidTest/manifest-merger-blame-debug-androidTest-report.txt
new file mode 100644
index 0000000..036fc0b
--- /dev/null
+++ b/node_modules/react-native-gesture-handler/android/build/intermediates/manifest_merge_blame_file/debugAndroidTest/manifest-merger-blame-debug-androidTest-report.txt
@@ -0,0 +1,36 @@
+1<?xml version="1.0" encoding="utf-8"?>
+2<manifest xmlns:android="http://schemas.android.com/apk/res/android"
+3    package="com.swmansion.gesturehandler.react.test" >
+4
+5    <uses-sdk
+5-->/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger208959645955249951.xml:5:5-74
+6        android:minSdkVersion="16"
+6-->/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger208959645955249951.xml:5:15-41
+7        android:targetSdkVersion="28" />
+7-->/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger208959645955249951.xml:5:42-71
+8
+9    <instrumentation
+9-->/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger208959645955249951.xml:11:5-15:89
+10        android:name="android.test.InstrumentationTestRunner"
+10-->/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger208959645955249951.xml:11:22-75
+11        android:functionalTest="false"
+11-->/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger208959645955249951.xml:14:22-52
+12        android:handleProfiling="false"
+12-->/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger208959645955249951.xml:13:22-53
+13        android:label="Tests for com.swmansion.gesturehandler.react.test"
+13-->/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger208959645955249951.xml:15:22-87
+14        android:targetPackage="com.swmansion.gesturehandler.react.test" />
+14-->/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger208959645955249951.xml:12:22-85
+15
+16    <application
+16-->/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger208959645955249951.xml:7:5-9:19
+17        android:appComponentFactory="androidx.core.app.CoreComponentFactory"
+17-->[androidx.core:core:1.0.1] /Users/brunolemos/.gradle/caches/transforms-2/files-2.1/6ebd315ab470d997b2cd255048b32130/core-1.0.1/AndroidManifest.xml:22:18-86
+18        android:debuggable="true" >
+18-->/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger208959645955249951.xml:7:18-43
+19        <uses-library android:name="android.test.runner" />
+19-->/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger208959645955249951.xml:8:9-60
+19-->/Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger208959645955249951.xml:8:23-57
+20    </application>
+21
+22</manifest>
diff --git a/node_modules/react-native-gesture-handler/android/build/intermediates/merged_manifests/debug/output.json b/node_modules/react-native-gesture-handler/android/build/intermediates/merged_manifests/debug/output.json
new file mode 100644
index 0000000..0fb7bd7
--- /dev/null
+++ b/node_modules/react-native-gesture-handler/android/build/intermediates/merged_manifests/debug/output.json
@@ -0,0 +1 @@
+[{"outputType":{"type":"MERGED_MANIFESTS"},"apkData":{"type":"MAIN","splits":[],"versionCode":1,"versionName":"1.0","enabled":true,"outputFile":"react-native-gesture-handler-debug.aar","fullName":"debug","baseName":"debug"},"path":"../../library_manifest/debug/AndroidManifest.xml","properties":{"packageId":"com.swmansion.gesturehandler.react","split":""}}]
\ No newline at end of file
diff --git a/node_modules/react-native-gesture-handler/android/build/intermediates/merged_manifests/debugAndroidTest/AndroidManifest.xml b/node_modules/react-native-gesture-handler/android/build/intermediates/merged_manifests/debugAndroidTest/AndroidManifest.xml
new file mode 100644
index 0000000..fb9ac8f
--- /dev/null
+++ b/node_modules/react-native-gesture-handler/android/build/intermediates/merged_manifests/debugAndroidTest/AndroidManifest.xml
@@ -0,0 +1,22 @@
+<?xml version="1.0" encoding="utf-8"?>
+<manifest xmlns:android="http://schemas.android.com/apk/res/android"
+    package="com.swmansion.gesturehandler.react.test" >
+
+    <uses-sdk
+        android:minSdkVersion="16"
+        android:targetSdkVersion="28" />
+
+    <instrumentation
+        android:name="android.test.InstrumentationTestRunner"
+        android:functionalTest="false"
+        android:handleProfiling="false"
+        android:label="Tests for com.swmansion.gesturehandler.react.test"
+        android:targetPackage="com.swmansion.gesturehandler.react.test" />
+
+    <application
+        android:appComponentFactory="androidx.core.app.CoreComponentFactory"
+        android:debuggable="true" >
+        <uses-library android:name="android.test.runner" />
+    </application>
+
+</manifest>
\ No newline at end of file
diff --git a/node_modules/react-native-gesture-handler/android/build/intermediates/merged_manifests/debugAndroidTest/output.json b/node_modules/react-native-gesture-handler/android/build/intermediates/merged_manifests/debugAndroidTest/output.json
new file mode 100644
index 0000000..1a761d6
--- /dev/null
+++ b/node_modules/react-native-gesture-handler/android/build/intermediates/merged_manifests/debugAndroidTest/output.json
@@ -0,0 +1 @@
+[{"outputType":{"type":"MERGED_MANIFESTS"},"apkData":{"type":"MAIN","splits":[],"versionCode":1,"versionName":"1.0","enabled":true,"outputFile":"react-native-gesture-handler-debug-androidTest.apk","fullName":"debugAndroidTest","baseName":"debug-androidTest"},"path":"AndroidManifest.xml","properties":{}}]
\ No newline at end of file
diff --git a/node_modules/react-native-gesture-handler/android/build/outputs/logs/manifest-merger-debug-report.txt b/node_modules/react-native-gesture-handler/android/build/outputs/logs/manifest-merger-debug-report.txt
new file mode 100644
index 0000000..13cbeb7
--- /dev/null
+++ b/node_modules/react-native-gesture-handler/android/build/outputs/logs/manifest-merger-debug-report.txt
@@ -0,0 +1,37 @@
+-- Merging decision tree log ---
+manifest
+ADDED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml:1:1-3:12
+INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml:1:1-3:12
+INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml:1:1-3:12
+INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml:1:1-3:12
+INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml:1:1-3:12
+INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml:1:1-3:12
+INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml:1:1-3:12
+	package
+		ADDED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml:2:5-49
+		INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml
+		INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml
+	android:versionName
+		INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml
+		ADDED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml:1:1-3:12
+		INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml
+	android:versionCode
+		INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml
+		ADDED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml:1:1-3:12
+		INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml
+	xmlns:android
+		ADDED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml:1:11-69
+uses-sdk
+INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml reason: use-sdk injection requested
+INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml
+INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml
+INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml
+INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml
+	android:targetSdkVersion
+		INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml
+		ADDED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml
+		INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml
+	android:minSdkVersion
+		INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml
+		ADDED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml
+		INJECTED from /Users/brunolemos/Projects/devhub/devhub/node_modules/react-native-gesture-handler/android/src/main/AndroidManifest.xml
diff --git a/node_modules/react-native-gesture-handler/android/lib/src/main/java/com/swmansion/gesturehandler/NativeViewGestureHandler.java b/node_modules/react-native-gesture-handler/android/lib/src/main/java/com/swmansion/gesturehandler/NativeViewGestureHandler.java
index ca69016..0a38f5b 100644
--- a/node_modules/react-native-gesture-handler/android/lib/src/main/java/com/swmansion/gesturehandler/NativeViewGestureHandler.java
+++ b/node_modules/react-native-gesture-handler/android/lib/src/main/java/com/swmansion/gesturehandler/NativeViewGestureHandler.java
@@ -5,6 +5,8 @@ import android.view.MotionEvent;
 import android.view.View;
 import android.view.ViewGroup;
 
+import com.swmansion.gesturehandler.react.RNGestureHandlerButtonViewManager;
+
 public class NativeViewGestureHandler extends GestureHandler<NativeViewGestureHandler> {
 
   private boolean mShouldActivateOnStart;
@@ -34,6 +36,18 @@ public class NativeViewGestureHandler extends GestureHandler<NativeViewGestureHa
     return super.shouldRequireToWaitForFailure(handler);
   }
 
+  private boolean isPreventedFromBeginning() {
+    // RNGestureHandlerButtonViewManager is connected with logic
+    // related to handling exclusive touches which should prevent
+    // another buttons from beginning gesture recognition.
+    View view = getView();
+    if (view instanceof RNGestureHandlerButtonViewManager.ButtonViewGroup) {
+      // setting flag for an exclusive touch for buttons
+      return !((RNGestureHandlerButtonViewManager.ButtonViewGroup) view).setResponder();
+    }
+    return false;
+  }
+
   @Override
   public boolean shouldRecognizeSimultaneously(GestureHandler handler) {
     if (handler instanceof NativeViewGestureHandler) {
@@ -53,7 +67,7 @@ public class NativeViewGestureHandler extends GestureHandler<NativeViewGestureHa
     int otherState = handler.getState();
 
     if (state == STATE_ACTIVE && otherState == STATE_ACTIVE && canBeInterrupted) {
-      // if both handlers are active and the current handler can be interruped it we return `false`
+      // if both handlers are active and the current handler can be interrupted it we return `false`
       // as it means the other handler has turned active and returning `true` would prevent it from
       // interrupting the current handler
       return false;
@@ -85,8 +99,9 @@ public class NativeViewGestureHandler extends GestureHandler<NativeViewGestureHa
       } else if (tryIntercept(view, event)) {
         view.onTouchEvent(event);
         activate();
-      } else if (state != STATE_BEGAN) {
+      } else if (state != STATE_BEGAN && !isPreventedFromBeginning()) {
         begin();
+
       }
     } else if (state == STATE_ACTIVE) {
       view.onTouchEvent(event);
diff --git a/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java b/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java
index fd625bd..c44aff2 100644
--- a/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java
+++ b/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java
@@ -21,7 +21,7 @@ import com.facebook.react.uimanager.annotations.ReactProp;
 public class RNGestureHandlerButtonViewManager extends
         ViewGroupManager<RNGestureHandlerButtonViewManager.ButtonViewGroup> {
 
-  static class ButtonViewGroup extends ViewGroup {
+  public static class ButtonViewGroup extends ViewGroup {
 
     static TypedValue sResolveOutValue = new TypedValue();
     static ButtonViewGroup sResponder;
@@ -32,6 +32,7 @@ public class RNGestureHandlerButtonViewManager extends
     boolean mUseForeground = false;
     boolean mUseBorderless = false;
     float mBorderRadius = 0;
+    private boolean mExclusive = true;
     boolean mNeedBackgroundUpdate = false;
 
 
@@ -50,6 +51,10 @@ public class RNGestureHandlerButtonViewManager extends
       mNeedBackgroundUpdate = true;
     }
 
+    public void setExclusive(boolean exclusive) {
+      mExclusive = exclusive;
+    }
+
     public void setRippleColor(Integer color) {
       mRippleColor = color;
       mNeedBackgroundUpdate = true;
@@ -167,14 +172,20 @@ public class RNGestureHandlerButtonViewManager extends
       }
     }
 
+    public boolean setResponder() {
+      if (sResponder == null) {
+        if (mExclusive) {
+          sResponder = this;
+        }
+        return true;
+      }
+      return false;
+    }
+
     @Override
     public void setPressed(boolean pressed) {
-      if (pressed && sResponder == null) {
-        // first button to be pressed grabs button responder
-        sResponder = this;
-      }
-      if (!pressed || sResponder == this) {
-        // we set pressed state only for current responder
+      if (!pressed || sResponder == this || (sResponder == null && !mExclusive)) {
+        // we set pressed state only for current responder if exclusive
         super.setPressed(pressed);
       }
       if (!pressed && sResponder == this) {
@@ -225,6 +236,11 @@ public class RNGestureHandlerButtonViewManager extends
     view.setRippleColor(rippleColor);
   }
 
+  @ReactProp(name = "exclusive", defaultBoolean = true)
+  public void setExclusive(ButtonViewGroup view, boolean exclusive) {
+    view.setExclusive(exclusive);
+  }
+
   @Override
   protected void onAfterUpdateTransaction(ButtonViewGroup view) {
     view.updateBackground();
```

</details>

**Comment by TuanLinhDang** [comment]
@brunolemos Can you please show me step to fix it bro? Im still struggling :)

**Comment by brunolemos** [comment]
@TuanLinhDang you need to follow the instructions at the [patch-package](https://github.com/ds300/patch-package) readme, which is basically installing `yarn add patch-package postinstall-postinstall`. Then, create a `patches` folder and a file named `react-native-gesture-handler+1.5.2.patch` on it with the contents I pasted above. Then run `yarn` so the patch gets applied.

**Comment by TuanLinhDang** [comment]
@brunolemos ok. Thanks in advance. Let me try now. One more question is where should I create the patches folder in, inside the android folder or in project?

**Comment by micheleb** [comment]
@brunolemos thanks for the patch! I noticed there are a few changes that are not necessary in order for the patch to work, and they point to paths to your local filesystem anyway, so here's the patch after removing those:
<details><summary>patches/react-native-gesture-handler+1.5.2.patch</summary>
<p>

```diff
diff --git a/node_modules/react-native-gesture-handler/android/build/generated/source/buildConfig/androidTest/debug/com/swmansion/gesturehandler/react/test/BuildConfig.java b/node_modules/react-native-gesture-handler/android/build/generated/source/buildConfig/androidTest/debug/com/swmansion/gesturehandler/react/test/BuildConfig.java
new file mode 100644
index 0000000..dc64a01
--- /dev/null
+++ b/node_modules/react-native-gesture-handler/android/build/generated/source/buildConfig/androidTest/debug/com/swmansion/gesturehandler/react/test/BuildConfig.java
@@ -0,0 +1,13 @@
+/**
+ * Automatically generated file. DO NOT MODIFY
+ */
+package com.swmansion.gesturehandler.react.test;
+
+public final class BuildConfig {
+  public static final boolean DEBUG = Boolean.parseBoolean("true");
+  public static final String APPLICATION_ID = "com.swmansion.gesturehandler.react.test";
+  public static final String BUILD_TYPE = "debug";
+  public static final String FLAVOR = "";
+  public static final int VERSION_CODE = 1;
+  public static final String VERSION_NAME = "1.0";
+}
diff --git a/node_modules/react-native-gesture-handler/android/build/generated/source/buildConfig/debug/com/swmansion/gesturehandler/react/BuildConfig.java b/node_modules/react-native-gesture-handler/android/build/generated/source/buildConfig/debug/com/swmansion/gesturehandler/react/BuildConfig.java
new file mode 100644
index 0000000..bd6dac7
--- /dev/null
+++ b/node_modules/react-native-gesture-handler/android/build/generated/source/buildConfig/debug/com/swmansion/gesturehandler/react/BuildConfig.java
@@ -0,0 +1,18 @@
+/**
+ * Automatically generated file. DO NOT MODIFY
+ */
+package com.swmansion.gesturehandler.react;
+
+public final class BuildConfig {
+  public static final boolean DEBUG = Boolean.parseBoolean("true");
+  public static final String LIBRARY_PACKAGE_NAME = "com.swmansion.gesturehandler.react";
+  /**
+   * @deprecated APPLICATION_ID is misleading in libraries. For the library package name use LIBRARY_PACKAGE_NAME
+   */
+  @Deprecated
+  public static final String APPLICATION_ID = "com.swmansion.gesturehandler.react";
+  public static final String BUILD_TYPE = "debug";
+  public static final String FLAVOR = "";
+  public static final int VERSION_CODE = 1;
+  public static final String VERSION_NAME = "1.0";
+}
diff --git a/node_modules/react-native-gesture-handler/android/lib/src/main/java/com/swmansion/gesturehandler/NativeViewGestureHandler.java b/node_modules/react-native-gesture-handler/android/lib/src/main/java/com/swmansion/gesturehandler/NativeViewGestureHandler.java
index ca69016..0a38f5b 100644
--- a/node_modules/react-native-gesture-handler/android/lib/src/main/java/com/swmansion/gesturehandler/NativeViewGestureHandler.java
+++ b/node_modules/react-native-gesture-handler/android/lib/src/main/java/com/swmansion/gesturehandler/NativeViewGestureHandler.java
@@ -5,6 +5,8 @@ import android.view.MotionEvent;
 import android.view.View;
 import android.view.ViewGroup;
 
+import com.swmansion.gesturehandler.react.RNGestureHandlerButtonViewManager;
+
 public class NativeViewGestureHandler extends GestureHandler<NativeViewGestureHandler> {
 
   private boolean mShouldActivateOnStart;
@@ -34,6 +36,18 @@ public class NativeViewGestureHandler extends GestureHandler<NativeViewGestureHa
     return super.shouldRequireToWaitForFailure(handler);
   }
 
+  private boolean isPreventedFromBeginning() {
+    // RNGestureHandlerButtonViewManager is connected with logic
+    // related to handling exclusive touches which should prevent
+    // another buttons from beginning gesture recognition.
+    View view = getView();
+    if (view instanceof RNGestureHandlerButtonViewManager.ButtonViewGroup) {
+      // setting flag for an exclusive touch for buttons
+      return !((RNGestureHandlerButtonViewManager.ButtonViewGroup) view).setResponder();
+    }
+    return false;
+  }
+
   @Override
   public boolean shouldRecognizeSimultaneously(GestureHandler handler) {
     if (handler instanceof NativeViewGestureHandler) {
@@ -53,7 +67,7 @@ public class NativeViewGestureHandler extends GestureHandler<NativeViewGestureHa
     int otherState = handler.getState();
 
     if (state == STATE_ACTIVE && otherState == STATE_ACTIVE && canBeInterrupted) {
-      // if both handlers are active and the current handler can be interruped it we return `false`
+      // if both handlers are active and the current handler can be interrupted it we return `false`
       // as it means the other handler has turned active and returning `true` would prevent it from
       // interrupting the current handler
       return false;
@@ -85,8 +99,9 @@ public class NativeViewGestureHandler extends GestureHandler<NativeViewGestureHa
       } else if (tryIntercept(view, event)) {
         view.onTouchEvent(event);
         activate();
-      } else if (state != STATE_BEGAN) {
+      } else if (state != STATE_BEGAN && !isPreventedFromBeginning()) {
         begin();
+
       }
     } else if (state == STATE_ACTIVE) {
       view.onTouchEvent(event);
diff --git a/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java b/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java
index fd625bd..c44aff2 100644
--- a/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java
+++ b/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java
@@ -21,7 +21,7 @@ import com.facebook.react.uimanager.annotations.ReactProp;
 public class RNGestureHandlerButtonViewManager extends
         ViewGroupManager<RNGestureHandlerButtonViewManager.ButtonViewGroup> {
 
-  static class ButtonViewGroup extends ViewGroup {
+  public static class ButtonViewGroup extends ViewGroup {
 
     static TypedValue sResolveOutValue = new TypedValue();
     static ButtonViewGroup sResponder;
@@ -32,6 +32,7 @@ public class RNGestureHandlerButtonViewManager extends
     boolean mUseForeground = false;
     boolean mUseBorderless = false;
     float mBorderRadius = 0;
+    private boolean mExclusive = true;
     boolean mNeedBackgroundUpdate = false;
 
 
@@ -50,6 +51,10 @@ public class RNGestureHandlerButtonViewManager extends
       mNeedBackgroundUpdate = true;
     }
 
+    public void setExclusive(boolean exclusive) {
+      mExclusive = exclusive;
+    }
+
     public void setRippleColor(Integer color) {
       mRippleColor = color;
       mNeedBackgroundUpdate = true;
@@ -167,14 +172,20 @@ public class RNGestureHandlerButtonViewManager extends
       }
     }
 
+    public boolean setResponder() {
+      if (sResponder == null) {
+        if (mExclusive) {
+          sResponder = this;
+        }
+        return true;
+      }
+      return false;
+    }
+
     @Override
     public void setPressed(boolean pressed) {
-      if (pressed && sResponder == null) {
-        // first button to be pressed grabs button responder
-        sResponder = this;
-      }
-      if (!pressed || sResponder == this) {
-        // we set pressed state only for current responder
+      if (!pressed || sResponder == this || (sResponder == null && !mExclusive)) {
+        // we set pressed state only for current responder if exclusive
         super.setPressed(pressed);
       }
       if (!pressed && sResponder == this) {
@@ -225,6 +236,11 @@ public class RNGestureHandlerButtonViewManager extends
     view.setRippleColor(rippleColor);
   }
 
+  @ReactProp(name = "exclusive", defaultBoolean = true)
+  public void setExclusive(ButtonViewGroup view, boolean exclusive) {
+    view.setExclusive(exclusive);
+  }
+
   @Override
   protected void onAfterUpdateTransaction(ButtonViewGroup view) {
     view.updateBackground();
```

</p>
</details>

Also, I noticed that if I click on a nested touchable that does something that doesn't require a re-render (e.g., if a button simply shows a Toast on android), the next time I click on it it will still trigger the outer touchable. Maybe the state is not reset after the click?

Not a big issue anyway, as usually clicks result in a re-render anyway, but just FYI.

Thanks again!

**Comment by brunolemos** [comment]
> there are a few changes that are not necessary in order for the patch to work, and they point to paths to your local filesystem anyway,

oh didn't notice, it's auto generated, updated!

> the next time I click on it it will still trigger the outer touchable. Maybe the state does not get reset after the click?

I didn't verify this but please comment it on #486 so maybe the author can fix this before merging

**Comment by FRizzonelli** [comment]
@brunolemos Thanks for sharing the patch, life saver <3 @kmagiera Do you think it's possible to merge it in master and release on NPM? I can confirm that without the patch, it's not working on Android. (Tested on version 61.5 and 1.5.2, both latest)

**Comment by AlexandreMaistret** [comment]
I am also encountering the same problem.

Did the patch has been pushed on master and available on NPM ?

**Comment by lucastonon** [comment]
I am still having this problem on 1.6.1

**Comment by punisher97** [comment]
+1 same problem

**Comment by punisher97** [comment]
I update patch to working with react-native-gesture-handler 1.6.1

```patch
diff --git a/node_modules/react-native-gesture-handler/android/lib/src/main/java/com/swmansion/gesturehandler/NativeViewGestureHandler.java b/node_modules/react-native-gesture-handler/android/lib/src/main/java/com/swmansion/gesturehandler/NativeViewGestureHandler.java
index ca69016..fdfa662 100644
--- a/node_modules/react-native-gesture-handler/android/lib/src/main/java/com/swmansion/gesturehandler/NativeViewGestureHandler.java
+++ b/node_modules/react-native-gesture-handler/android/lib/src/main/java/com/swmansion/gesturehandler/NativeViewGestureHandler.java
@@ -4,6 +4,7 @@ import android.os.SystemClock;
 import android.view.MotionEvent;
 import android.view.View;
 import android.view.ViewGroup;
+import com.swmansion.gesturehandler.react.RNGestureHandlerButtonViewManager;

 public class NativeViewGestureHandler extends GestureHandler<NativeViewGestureHandler> {

@@ -13,7 +14,17 @@ public class NativeViewGestureHandler extends GestureHandler<NativeViewGestureHa
   public NativeViewGestureHandler() {
     setShouldCancelWhenOutside(true);
   }
-
+  private boolean isPreventedFromBeginning() {
+    // RNGestureHandlerButtonViewManager is connected with logic
+    // related to handling exclusive touches which should prevent
+    // another buttons from beginning gesture recognition.
+    View view = getView();
+    if (view instanceof RNGestureHandlerButtonViewManager.ButtonViewGroup) {
+      // setting flag for an exclusive touch for buttons
+      return !((RNGestureHandlerButtonViewManager.ButtonViewGroup) view).setResponder();
+    }
+    return false;
+  }
   public NativeViewGestureHandler setShouldActivateOnStart(boolean shouldActivateOnStart) {
     mShouldActivateOnStart = shouldActivateOnStart;
     return this;
@@ -85,7 +96,7 @@ public class NativeViewGestureHandler extends GestureHandler<NativeViewGestureHa
       } else if (tryIntercept(view, event)) {
         view.onTouchEvent(event);
         activate();
-      } else if (state != STATE_BEGAN) {
+      } else if (state != STATE_BEGAN && !isPreventedFromBeginning()) {
         begin();
       }
     } else if (state == STATE_ACTIVE) {
diff --git a/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java b/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java
index fd625bd..250f1c3 100644
--- a/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java
+++ b/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java
@@ -21,11 +21,11 @@ import com.facebook.react.uimanager.annotations.ReactProp;
 public class RNGestureHandlerButtonViewManager extends
         ViewGroupManager<RNGestureHandlerButtonViewManager.ButtonViewGroup> {

-  static class ButtonViewGroup extends ViewGroup {
+  public static class ButtonViewGroup extends ViewGroup {

     static TypedValue sResolveOutValue = new TypedValue();
     static ButtonViewGroup sResponder;
-
+    private boolean mExclusive = true;
     int mBackgroundColor = Color.TRANSPARENT;
     // Using object because of handling null representing no value set.
     Integer mRippleColor;
@@ -44,6 +44,10 @@ public class RNGestureHandlerButtonViewManager extends
       mNeedBackgroundUpdate = true;
     }

+    public void setExclusive(boolean exclusive) {
+      mExclusive = exclusive;
+    }
+
     @Override
     public void setBackgroundColor(int color) {
       mBackgroundColor = color;
@@ -55,6 +59,16 @@ public class RNGestureHandlerButtonViewManager extends
       mNeedBackgroundUpdate = true;
     }

+    public boolean setResponder() {
+      if (sResponder == null) {
+        if (mExclusive) {
+          sResponder = this;
+        }
+        return true;
+      }
+      return false;
+    }
+
     public void setBorderRadius(float borderRadius) {
       mBorderRadius = borderRadius * (float)getResources().getDisplayMetrics().density;
       mNeedBackgroundUpdate = true;
@@ -173,7 +187,7 @@ public class RNGestureHandlerButtonViewManager extends
         // first button to be pressed grabs button responder
         sResponder = this;
       }
-      if (!pressed || sResponder == this) {
+      if (!pressed || sResponder == this || (sResponder == null && !mExclusive)) {
         // we set pressed state only for current responder
         super.setPressed(pressed);
       }
@@ -225,6 +239,11 @@ public class RNGestureHandlerButtonViewManager extends
     view.setRippleColor(rippleColor);
   }

+  @ReactProp(name = "exclusive", defaultBoolean = true)
+  public void setExclusive(ButtonViewGroup view, boolean exclusive) {
+    view.setExclusive(exclusive);
+  }
+
   @Override
   protected void onAfterUpdateTransaction(ButtonViewGroup view) {
     view.updateBackground();
```

**Comment by akug17** [comment]
I tried TouchableOpacity from 'react-native' lib it works fine

**Comment by PatricioBedregal** [comment]
I think this issue also affects if you try to use `createNativeStackNavigator` from react-native-screens, because when I set that stack navigator all my Touchables from react-native-gesture-handler stops working

**Comment by matt-dalton** [comment]
@punisher97 Do you happen to know if the equivalent patch will work with 1.7.0? I just tried upgrading and added the same changes, and unfortunately it seems like presses aren't being registered. I can't really work out why as it doesn't look like this [code has changed](https://github.com/software-mansion/react-native-gesture-handler/compare/1.6.1...1.7.0)

**Comment by pmutshipayi** [comment]
> I tried TouchableOpacity from 'react-native' lib it works fine

Thank you, works for me too

**Comment by lightrow** [comment]
1.8.0 same problem

**Comment by matinzd** [comment]
Me too,
I can not use touchable opacity inside the Swipeable component.

**Comment by huyhai** [comment]
same

**Comment by yuichi-saito-howtv** [comment]
> clicking on a nested View clicks on the View below

Sorry for referring to the above issue.
I would appreciate it if you could ignore it.

**Comment by cokepizza** [comment]
same issue 1.9.0 in android
touch events bubble inside multiple overlapping touch areas

**Comment by a-eid** [comment]
still an issue in `^1.9.0`.

**Comment by zachgibson** [comment]
I switched to using the Button components which have basically all the feedback styles you'd want but more importantly they work when nested.

**Comment by yfunk** [comment]
> I switched to using the Button components which have basically all the feedback styles you'd want but more importantly they work when nested.

That's actually pretty interesting, since from what I can tell the all the Touchables Gesture Handler exports are effectively just wrappers around `BaseButton`. Maybe the issue that causes the parents of nested Touchables to also be pressed is somewhere in the implementation of [`GenericTouchable.js`](https://github.com/software-mansion/react-native-gesture-handler/blob/master/src/components/touchables/GenericTouchable.js)?

**Comment by dandre-hound** [comment]
Yeah I've been experiencing this same issue, it's pretty frustrating and I haven't found a solution yet. I thought this is what `waitFor` was used for...?

**Comment by florian-milky** [comment]
> I switched to using the Button components which have basically all the feedback styles you'd want but more importantly they work when nested.

I can confirm that using a BaseButton instead of a TouchableOpacity in the outer component works as expected!

**Comment by congdoKnovva** [comment]
for Android, import the outer component from 'react-native'
import { TouchableOpacity as NativeTouchableOpacity, Platform } from 'react-native';
import { TouchableOpacity as GHTouchableOpacity } from 'react-native-gesture-handler'
const TouchableOpacity = Platform.OS === 'ios' ? GHTouchableOpacity : NativeTouchableOpacity;

**Comment by tankers746** [comment]
Passing `disallowInterruption={true}` to the touchable should fix this. 
```
<TouchableOpacity {...props} disallowInterruption={true} />,
```

Should this be enabled by default in GenericTouchable?

**Comment by yfunk** [comment]
@tankers746 This is a nice solution for when you are only using `onPress` (just like switching to `Button`). Unfortunately it doesn't work for any of the other events (`onPressIn`, `onPressOut` and `onLongPress`), so I don't think it should be enabled by default.

**Comment by jotahws** [comment]
> Passing `disallowInterruption={true}` to the touchable should fix this.
> 
> ```
> <TouchableOpacity {...props} disallowInterruption={true} />,
> ```
> 
> Should this be enabled by default in GenericTouchable?

Thanks @tankers746 that works like a charm. 

This solution also work for `TouchableWithoutFeedback`. The prop may be put just on the nested Component that it will work anyway

**Comment by ezhkov** [comment]
Hello. Any news about this? I have another workaround: tap on Switch inside TouchableOpacity not working. 
https://snack.expo.io/@ezhkov/rngh-nested-touchable-android-bug

**Comment by soryuu** [comment]
> Passing `disallowInterruption={true}` to the touchable should fix this.
> 
> ```
> <TouchableOpacity {...props} disallowInterruption={true} />,
> ```
> 
> Should this be enabled by default in GenericTouchable?

Still doesn't work even with topic starter snack example:
https://snack.expo.io/zPzk7M9t7 (added **disallowInterruption** prop)

is there any actual solutions at this moment for this issue?

Maybe there is new patch for latest version?

**Comment by janicduplessis** [comment]
Seems like the issue happens on web too. I made a snack repro that shows the different behaviour with Touchable from react-native and react-native-gesture-handler. https://snack.expo.dev/JEnwHDo1h

**Comment by hollyos** [comment]
Using `TouchableWithoutFeedback` as the outer wrapper solved the issue for me.

```
<TouchableWithoutFeedback>
  <TouchableOpacity>
    <Text>Click ME</Text>
  </TouchableOpacity>
</TouchableWithoutFeedback>
```
